### PR TITLE
RSDK-2013 Update orb-grpb-server.rb

### PR DESCRIPTION
**Pull request by zaporter-work**
Ticket: https://viam.atlassian.net/browse/RSDK-2013

Update the formula to point to the new viam-orb-slam3 repo since we moved orbslam3 out of the slam repo into its own repo.

This is a clone of https://github.com/viamrobotics/homebrew-brews/pull/18

### CODE REVIEW

**Review by kkufieta — APPROVED** [review]
LGTM - Tested on MacOS x86_64 successfully.

**Review by tessavitabile — APPROVED** [review]

**Comment by zaporter-work** [comment]
Nick has just successfully built on macOS with an M1

**Review by nicksanford — APPROVED** [review]

**Review by Otterverse — CHANGES_REQUESTED** [review]
Talking with Zack directly, but this fails to build on my M1 mac at the moment. Suspect something changed with upstream pango and our pangolin, and or the build tools (cmake, etc.) Has RPATH problems the install_name_tool isn't fixing. Probably needs CMAKE changes per: https://github.com/viamrobotics/homebrew-brews/pull/4#issuecomment-1294217669

Note, this isn't new, the old formula (before this) is broken as well, and rolling back doesn't appear to fix it either.

**Review by Otterverse — APPROVED** [review]
Great job on figuring out the fix in pangolin! It builds correctly for me, so approving, but with one change needed... you need to add a "revision" to the pangolin formula so people will get updated to the new version if they already had an older version installed. https://docs.brew.sh/Formula-Cookbook#formulae-revisions (basically just put `revision 1` as a new line right below the sha256 line near the top.)

**Pull request merged**
